


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "bronze";


ALTER SCHEMA "bronze" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "dbt_dev_gold";


ALTER SCHEMA "dbt_dev_gold" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "dbt_dev_silver";


ALTER SCHEMA "dbt_dev_silver" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "dbt_gold";


ALTER SCHEMA "dbt_gold" OWNER TO "postgres";


CREATE SCHEMA IF NOT EXISTS "dbt_silver";


ALTER SCHEMA "dbt_silver" OWNER TO "postgres";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "bronze"."bronze_api_logs" (
    "log_id" bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    "user_id" character varying(255),
    "endpoint" character varying(500) NOT NULL,
    "http_method" character varying(10) NOT NULL,
    "status_code" integer NOT NULL,
    "response_time_ms" integer,
    "request_body" "jsonb",
    "response_body" "jsonb",
    "ip_address" "inet",
    "user_agent" "text",
    "ingested_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "bronze"."bronze_api_logs" OWNER TO "postgres";


ALTER TABLE "bronze"."bronze_api_logs" ALTER COLUMN "log_id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "bronze"."bronze_api_logs_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "bronze"."bronze_users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "bronze"."bronze_users" OWNER TO "postgres";


ALTER TABLE "bronze"."bronze_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "bronze"."bronze_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "dbt_dev_gold"."gold_api_logs_daily" (
    "created_day" "date",
    "status" "text",
    "count" bigint
);


ALTER TABLE "dbt_dev_gold"."gold_api_logs_daily" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "dbt_dev_silver"."silver_api_logs" (
    "log_id" bigint,
    "timestamp" timestamp with time zone,
    "user_id" character varying(255),
    "endpoint" character varying(500),
    "http_method" character varying(10),
    "status_code" integer,
    "status" "text",
    "response_time_ms" integer,
    "response_body" "jsonb",
    "ip_address" "inet",
    "user_agent" "text",
    "ingested_at" timestamp without time zone
);


ALTER TABLE "dbt_dev_silver"."silver_api_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "dbt_gold"."gold_api_logs_daily" (
    "created_day" "date",
    "status" "text",
    "count" bigint
);


ALTER TABLE "dbt_gold"."gold_api_logs_daily" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "dbt_silver"."silver_api_logs" (
    "log_id" bigint,
    "timestamp" timestamp with time zone,
    "user_id" character varying(255),
    "endpoint" character varying(500),
    "http_method" character varying(10),
    "status_code" integer,
    "status" "text",
    "response_time_ms" integer,
    "response_body" "jsonb",
    "ip_address" "inet",
    "user_agent" "text",
    "ingested_at" timestamp without time zone
);


ALTER TABLE "dbt_silver"."silver_api_logs" OWNER TO "postgres";


ALTER TABLE ONLY "bronze"."bronze_api_logs"
    ADD CONSTRAINT "bronze_api_logs_pkey" PRIMARY KEY ("log_id");



ALTER TABLE ONLY "bronze"."bronze_users"
    ADD CONSTRAINT "bronze_users_pkey" PRIMARY KEY ("id");



ALTER TABLE "bronze"."bronze_users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";














































































































































































ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































