
  create table "bronze"."bronze_users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "bronze"."bronze_users" enable row level security;

CREATE UNIQUE INDEX bronze_users_pkey ON bronze.bronze_users USING btree (id);

alter table "bronze"."bronze_users" add constraint "bronze_users_pkey" PRIMARY KEY using index "bronze_users_pkey";


